apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-plantuml.example.com
spec:
  secretName: tls-plantuml.example.com
  dnsNames:
  - plantuml.example.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - plantuml.example.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
